name: Publish Package
on:
  release:
    types: [created] # Mieux vaut trigger sur une release que sur un push de tag

permissions:
  contents: read
  id-token: write # Indispensable pour que NPM trust GitHub

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24' # Utilise une version LTS stable
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      
      # C'est ici que tout se joue :
      - run: npm publish --provenance --access public
        env:
          # setup-node a créé un .npmrc qui attend cette variable.
          # On lui donne le token GitHub par défaut pour qu'il soit content.
          # L'auth réelle se fera via '--provenance' (OIDC).
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}